name: gym_club_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  bloc: ^9.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.12.0
  flutter_localizations:
    sdk: flutter
  get_it: ^9.0.5
  http: ^1.2.1
  intl: any
  jwt_decoder: ^2.0.1
  page_view_dot_indicator: ^2.3.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
